Shopping/urls.py
from django.urls import path, include
from .views import *

app_name = 'Shopping'

urlpatterns = [
    path("", index, name="Shopping"),
    path("ContactUs", ContactUs, name='ContactUs'),
    path('login', loginUser, name='login'),
    path('logout', UserLogout, name='logout'),
    path('signupform', signupform, name='signupform'),
    path('search', product_search.as_view(), name='search'),
    path('Detail/<pk>/', Detail, name='Detail'),
    # path('AllProduct/<item>/',AllProduct.as_view(),name='AllProduct'),
    path('AllProduct', AllProduct, name='AllProduct'),
    path('categorydata', categorydata, name='categorydata'),
    path('cart/add/<int:id>/', cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         item_increment, name='item_increment'),
    path('cart/item_increment_qty/<int:id>/<int:qty>/',
         item_increment_qty, name='item_increment_qty'),
    path('cart/item_decrement/<int:id>/', item_decrement, name='item_decrement'),
    path('cart/cart_clear/', cart_clear, name='cart_clear'),
    path('cart/cart-detail/', cart_detail, name='cart_detail'),
    path('checkout', checkout_form, name='checkout'),
    path('thanks', thanksyou, name='thanks'),
    path('myaccount', MyAccount.as_view(), name='myaccount'),
    path('bill/billdetail/<int:id>', billdetailspage, name="billdetail"),
    path('TrackingModel', TrackingView.as_view(), name="TrackingModel"),
    path('News', newsupdate, name="News"),
    path('unsubscribe', unsubscribe, name="unsubscribe"),
    path('APIview', APIview.as_view(), name="APIview"),
    path('APIviewSignUp', APIviewSignUp.as_view(), name="APIviewSignUp"),
    path('accDetail', accDetail, name='accDetail'),
    path('wishlist/add/<int:id>/', wistlist_add, name='wishlist'),
    path('wishlist/delete/<int:id>/', remove_wishlist_item, name='wishlistdelete'),
    path('wishlist_detail', wistlist_detail, name='wishlist_detail'),
    path('wishlistdeleteall', wishlistdeleteall, name='wishlistdeleteall'),
    path('compareList/add/<int:id>/', compareList_add, name='compareList'),
    path('compareList_detail', compareList_detail, name='compareList_detail'),
    path('compareListdeleteall', compareListdeleteall, name='compareListdeleteall'),
    path('ForgetEmail', ForgetEmail, name='change_password'),
    path('forgetPasswordPage', forgetPasswordPage, name='forgetPasswordPage'),
    path('change_password', change_password, name='change_password'),
    path('applyCouponCode', applyCouponCode, name='applyCouponCode'),
    path('cancelorder', cancelorder, name='cancelorder'),
    path('myprofile', myprofile, name='myprofile'),
    path('staff_profile', staff_profile.as_view(), name='staff_profile'),
    path('staff_profile_update/<int:id>/', staff_profile_update, name='staff_profile_update'),
    path('review', review, name='review'),
    path('comment', comment, name='comment'),
    path('loadcomment', loadcomment, name='loadcomment'),
    path('term_condition', Term_Condition.as_view(), name='term_condition'),
    path('policy', Policy.as_view(), name='policy'),
    path('commentpage', commentpage, name='commentpage'),
]

ShoppingMVC/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',include('Shopping.urls')),
    path('Shopping/',include('Shopping.urls')),
    path('Shopping/ShoppingAPI/',include('Shopping.ShoppingAPI.urls')),
]

templates/confirmation.html
{% extends 'base.html' %}{% load static %}{% block content %}

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Confirmation</h1>
                <nav class="d-flex align-items-center">
                    <a href="/Shopping">Home<span class="lnr lnr-arrow-right"></span></a>
                    <a href="#">Confirmation</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->

<!--================Order Details Area =================-->
<section class="order_details section_gap">
    <div class="container">
        <h3 class="title_confirmation">Thank you. Your order has been received.</h3>
        <div class="row order_d_inner">
            <div class="col-lg-4">
                <div class="details_item">
                    <h4>Order Info</h4>
                    <ul class="list">
                        <li><a href="#"><span>Order number</span> : {{ orderbill.pk }}</a></li>
                        <li><a href="#"><span>Date</span> : {{ orderbill.datetime }}</a></li>
                        <li><a href="#"><span>Total</span> : {{ orderbill.grandtotal }}</a></li>
                        <li><a href="#"><span>Payment method</span> : {{ orderbill.payment_method }}</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="details_item">
                    <h4>Personal Info</h4>
                    <ul class="list">
                        <li><a href="#"><span>Name</span> : {{ orderbill.fname }} {{ orderbill.lname }}</a></li>
                        <li><a href="#"><span>Email</span> : {{ orderbill.email }}</a></li>
                        <li><a href="#"><span>Mobile Number</span> : {{ orderbill.phn }}</a></li>
                        <li><a href="#"><span>Applied Coupon </span> : {{ orderbill.coupon }}</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="details_item">
                    <h4>Shipping Address</h4>
                    <ul class="list">
                        <li><a href="#"><span>Street</span> : {{ orderbill.addr }}</a></li>
                        <li><a href="#"><span>City</span> : {{ orderbill.city }}</a></li>
                        <li><a href="#"><span>Postcode </span> : {{ orderbill.zipcode }}</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="order_details_table">
            <h2>Order Details</h2>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Product</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in orderbilldetail %}
                        <tr>
                            <td>
                                <p>{{ i.proid.name }}</p>
                            </td>
                            <td>
                                <h5>x {{ i.qty }}</h5>
                            </td>
                            <td>
                                <p>&#8377; {{ i.price }}</p>
                            </td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td>
                            <h4>Net Amount</h4>
                        </td>
                        <td>
                            <h5></h5>
                        </td>
                        <td>
                            <p>&#8377; {{ orderbill.nettotal }}</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h4>GST</h4>
                        </td>
                        <td>
                            <h5></h5>
                        </td>
                        <td>
                            <p>{{ orderbill.GST }}%</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h4>Applied Coupon</h4>
                        </td>
                        <td>
                            <h5></h5>
                        </td>
                        <td>
                            <p>&#8377; {% if orderbill.coupon %}
                            {{ orderbill.coupon.price }
                                {% else %}
                                0
                            {% endif %}
                                </p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h4>Total</h4>
                        </td>
                        <td>
                            <h5></h5>
                        </td>
                        <td>
                            <p>&#8377; {{ orderbill.grandtotal }}</p>
                        </td>
                    </tr>
                    </tbody>
                </table>
            <div class="container">
                <div class="text-center">
                    <a href="{% url 'Shopping:thanks' %}?action=viewpdf&billid={{ orderbill.pk }}" target="_blank" class="btn btn-lg btn-outline-primary">View Bill</a>
                    <a href="{% url 'Shopping:thanks' %}?action=downloadpdf&billid={{ orderbill.pk }}" class="btn btn-lg btn-outline-success">Download Bill</a>
                </div>
            </div>
            </div>
        </div>
    </div>
</section>
<!--================End Order Details Area =================-->
{% endblock %}

templates/footer.html
{% load static %}
<footer class="footer-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>About Us</h6>
                    <p>
                        “Recently, the US Federal government banned online casinos from operating in America by making
                        it illegal to transfer money to them through any US bank or payment system. As a result of this
                        law, most of the popular online casino networks such as Party Gaming and PlayTech left the
                        United States.
                    </p>
                </div>
            </div>
            <div class="col-lg-4  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Newsletter</h6>
                    <p>Stay update with our latest</p>
                    <div class="" id="mc_embed_signup">
                        <form novalidate="true" action="{% url 'Shopping:News' %}?next={{ request.get_full_path }}"
                              method="post" class="form-inline">
                            {% csrf_token %}
                            <div class="d-flex flex-row">
                                <input class="form-control" name="nwem" id="nwem" placeholder="Enter Email"
                                       onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
                                       required="" type="email">
                                <button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right"
                                                                             aria-hidden="true"></i></button>
                                <div style="position: absolute; left: -5000px;">
                                    <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value=""
                                           type="text">
                                </div>
                            </div>
                            <div class="info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>API Reference</h6>
                    <ul style="list-style: none" id="footerAPI">
                        <li><a href="{% url 'Shopping:APIview' %}" class="footer-text">API Login</a></li>
                        <li><a href="{% url 'Shopping:APIviewSignUp' %}">API Sign up</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Terms and Policy</h6>
                    <ul style="list-style: none" id="footerAPI">
                        {#                        <li><a href="https://www.termsfeed.com/live/bfb4a18e-a54f-4cec-987f-dc5045c69765" class="footer-text">Terms & Conditions</a></li>#}
                        <li><a href="{% url 'Shopping:term_condition' %}" class="footer-text">Terms & Conditions</a></li>
                        <li><a href="{% url 'Shopping:policy' %}" class="footer-text">Privacy Policy</a></li>
{#                        <li><a href="https://www.termsfeed.com/live/359896f3-e3db-4eef-9897-f58ba22a4de0" class="footer-text">Privacy Policy</a></li>#}
                    </ul>
                    {#                    <p>Let us be social</p>#}
                    {#                    <div class="footer-social d-flex align-items-center">#}
                    {#                        <a target="_blank" href="https://www.facebook.com/karmastore.in/"><i class="fa fa-facebook"></i></a>#}
                    {#                        <a target="_blank" href="https://twitter.com/karmastore?lang=en"><i class="fa fa-twitter"></i></a>#}
                    {#                        <a target="_blank" href="https://dribbble.com/shots/4110772-Karma"><i class="fa fa-dribbble"></i></a>#}
                    {#                        <a target="_blank" href="https://www.behance.net/dima_karma"><i class="fa fa-behance"></i></a>#}
                    {#                    </div>#}
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.sticky.js' %}"></script>
<script src="{% static 'js/nouislider.min.js' %}"></script>
<script src="{% static 'js/countdown.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<!--gmaps Js-->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
<script src="{% static 'js/gmaps.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'mymain.js' %}"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
{#<script src="{% static 'Input-Field-Star-Rating-Plugin-jQuery/jquery-3.2.1.slim.min.js' %}"></script>#}
<script src="{% static 'Input-Field-Star-Rating-Plugin-jQuery/js/simple-rating.js' %}"></script>
<script>
    $(function () {
        $("#accordion").accordion();
    });
</script>
{% if message %}
    <script>
        $('.toast').toast('show');
    </script>
{% endif %}

templates/forgetchangepassword.html
{% extends 'base.html' %}{% load static %}
{% block content %}

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Change Password</h1>
                <nav class="d-flex align-items-center">
                    <a href="/Shopping">Home<span class="lnr lnr-arrow-right"></span></a>
                    <a href="#">Change Password</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->
<section class="login_box_area section_gap">
    <div class="display-4 font-weight-bold text-center text-uppercase">Forget Password</div>
</section>

<!--================Login Box Area =================-->
<section>
    <div class="container">
        <div class="jumbotron w-50 mx-auto">
            <form method="post" action="{% url 'Shopping:forgetPasswordPage' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" name="emailps" readonly class="form-control" value="{{ email }}">
                </div>
                <div class="form-group">
                    <label for="email">Password</label>
                    <input type="password" name="password1" id="id_new_password1" class="form-control">
                </div>
                <div class="form-group">
                    <label for="email">Confirm Password</label>
                    <input type="password" name="password2" id="id_new_password2" class="form-control">
                </div>
                <input type="checkbox" onclick="myFunction()">Show Password
                <div class="form-group text-center">
                    <button type="submit" class="btn primary-btn">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}
{% block styleblock %}

    <style>
        .clr-btn {
            border: none;
            position: relative;
            overflow: hidden;
            color: #fff;
            padding: 0 30px;
            line-height: 50px;
            border-radius: 0px;
            display: inline-block;
            text-transform: uppercase;
            font-weight: 500;
            cursor: pointer;
            -webkit-transition: all 0.3s ease 0s;
            -moz-transition: all 0.3s ease 0s;
            -o-transition: all 0.3s ease 0s;
            transition: all 0.3s ease 0s;
            width: 75%;
            margin: 0 auto;
        }
    </style>
{% endblock styleblock %}
{% block blockjs %}

<script>
    function myFunction() {
        var y = document.getElementById("id_new_password2");
        var z = document.getElementById("id_new_password1");
        if (y.type === "password") {
            y.type = 'text';
            z.type = 'text';
        } else {
            y.type = "password";
            z.type = "password";
        }
    }
</script>
<br><br><br><br>
{% endblock blockjs %}

templates/login.html
{% extends 'base.html' %}{% load static %}{% block content %}

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb form-control">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Login/Register</h1>
                <nav class="d-flex align-items-center">
                    <a href="/Shopping">Home<span class="lnr lnr-arrow-right"></span></a>
                    <a href="category.html">Login/Register</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->

<!--================Login Box Area =================-->
<section class="login_box_area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="login_box_img">
                    <img class="img-fluid" src="{% static 'img/login.jpg' %}" alt="">
                    <div class="hover">
                        <h4>New to our website?</h4>
                        <p>There are advances being made in science and technology everyday, and a good example of this
                            is the</p>
                        <a class="primary-btn" href="{% url 'Shopping:signupform' %}">Create an Account</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6" id="id_show">
                <div class="login_form_inner" id="id_forogemailform" style="display: none">
                    <h3>Forget Password</h3>
                    <form class="row login_form" method="post" id="forgetForm" novalidate="novalidate">
                        {% csrf_token %}
                        <div class="col-md-12 form-group" id="id_forgemaildiv">
                            <input type="email" name="forgemail" id="id_forgemial" required class="form-control"
                                   placeholder="Confirmation Email">
                        </div>
                        <div class="col-md-12 form-group">
                            <button type="submit" value="submit" class="primary-btn">Send Email</button>
                        </div>
                        <div class="col-md-12 form-group d-flex">
                            <a href="/Shopping">Home</a> &nbsp;&nbsp;<a id="changeformdiv">Login</a>
                        </div>

                    </form>
                </div>
                <div class="login_form_inner" id="show_email_form">
                    <h3>Log in to enter</h3>
                    <form class="row login_form" method="post" id="contactForm" novalidate="novalidate">
                        {% csrf_token %}
                        {#                    {{ form.error_messages }}#}
                        {% if messages %}
                            {% for value in messages %}
                                <ul class="errorlist">
                                    <li>{{ value }}</li>
                                </ul>
                            {% endfor %}

                        {% endif %}
                        {% for foo in form %}
                            <div class="col-md-12 form-group">
                                {{ foo }}
                            </div>
                        {% endfor %}
                        <div class="col-md-12 form-group">
                            <div class="creat_account">
                                <input type="checkbox" id="f-option2" name="selector">
                                <label for="f-option2">Keep me logged in</label>
                            </div>
                        </div>
                        <div class="col-md-12 form-group">
                            <button type="submit" value="submit" class="primary-btn">Log In</button>
                            <a id="changeform">Forgot Password?</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block blockjs %}


<!--================End Login Box Area =================-->
<script>
    document.getElementById('id_username').placeholder = 'Email';
    document.getElementById('id_username').type = 'email';
    document.getElementById('id_username').classList.add('form-control');
    document.getElementById('id_password').placeholder = 'Password';
    document.getElementById('id_password').classList.add('form-control');

    document.getElementById('changeform').addEventListener('click', function () {
        $('#show_email_form').slideUp();
        $('#id_forogemailform').fadeIn();
    })
    document.getElementById('changeformdiv').addEventListener('click', function () {
        $('#show_email_form').fadeIn();
        $('#id_forogemailform').slideUp();
    })

    document.getElementById('forgetForm').addEventListener('submit', function (e) {
        e.preventDefault();
        var forgemail = document.getElementById('id_forgemial').value;
        var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
        if (forgemail=="") {
            document.getElementById('id_forgemaildiv').innerHTML = document.getElementById('id_forgemial').outerHTML + '<p style="color: red">Please Fill the Required Field</p>'
        }else if (reg.test(forgemail)==false){
             document.getElementById('id_forgemaildiv').innerHTML = document.getElementById('id_forgemial').outerHTML + '<p style="color: red">Invalid Email</p>'
        }
        else {
            var xml=new XMLHttpRequest();
            xml.onreadystatechange = function () {
                if (this.readyState==4 && this.status==200){
                    var output = this.response;
                    if (String(output).includes('Error')) {
                        document.getElementById('id_forgemaildiv').innerHTML = document.getElementById('id_forgemial').outerHTML + `<p style="color: red">${output}</p>`;
                    }else{
                        document.getElementById('id_forgemaildiv').innerHTML = document.getElementById('id_forgemial').outerHTML + `<p style="color: dodgerblue">${output}</p>`;
                    }
                }
            };
            xml.open('GET','/Shopping/ForgetEmail?email='+forgemail,true);
            xml.send();
        }
    })


</script>
{% endblock %}

templates/thank.html
{% extends 'base.html' %}{% load static %}{% block content %}

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Thank You!</h1>
                <nav class="d-flex align-items-center">
                    <a href="/Shopping">Home<span class="lnr lnr-arrow-right"></span></a>
                    <a>Thank you!</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->

<!--================Contact Area =================-->
<section class="contact_area section_gap_bottom">
    <div class="container">
        <div class="mx-auto m-5 w-50" style="line-height: 9rem">
            <div class="display-4 font-weight-bold" style="color: #ffba00">Thanks for Shopping With Us</div>
            <h2 class="text-center" style="margin: 25px">Your BILL ID is : {{ billid }}</h2>
            <a href="{% url 'Shopping:Shopping' %}" class="btn primary-btn text-white w-100">More Shopping</a>
        </div>
    </div>
</section>
<!--================Contact Area =================-->
{% endblock %}

templates/wistlistdetail.html
{% extends 'base.html' %}{% load static %}{% block content %}

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>My WishList</h1>
                <nav class="d-flex align-items-center">
                    <a href="/Shopping">Home<span class="lnr lnr-arrow-right"></span></a>
                    <a href="#">WishList</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->
<section class="login_box_area section_gap">
    <div class="display-4 font-weight-bold text-center">My WishList</div>
</section>

<!--================Login Box Area =================-->
<section>
    <div class="container">
        <div class="row">
            {% if request.session.wishlist %}
                {% for i in request.session.wishlist %}
                    <div class="col-lg-3 col-md-6">
                        <div class="single-product">
                            <img class="img-fluid" src="{% static 'media/' %}{{ i.pic }}" alt="">
                            <div class="product-details">
                                <h6>{{ i.name }}</h6>
                                <div class="price">
                                    <h6>&#8377; {{ i.price }}</h6>
                                    <h6 class="l-through">{{ i.discount }}</h6>
                                </div>
                                <div class="prd-bottom">
                                    <a onclick="cart({{ i.id }})" class="social-info mycart">
                                        <span class="ti-bag"></span>
                                        <p class="hover-text">add to bag</p>
                                    </a>
                                    <a href="{% url 'Shopping:wishlistdelete' i.id %}?next={{ request.get_full_path }}"
                                       class="social-info mycart">
                                        <span class="lnr lnr-trash"></span>
                                        <p class="hover-text">Remove</p>
                                    </a>
                                    <a href="{% url 'Shopping:Detail' i.id %}" class="social-info mycart">
                                        <span class="lnr lnr-move"></span>
                                        <p class="hover-text">view more</p>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="col-lg-12 col-md-12">
                    <div class="display-1 text-center text-danger font-weight-bold">! No Product Found</div>
                    <br><br><br>
                </div>
            {% endif %}
            <div class="col-md-12 form-group text-center">
                <a class="primary-btn clr-btn" href="{% url 'Shopping:wishlistdeleteall' %}?next={{ request.get_full_path }}">Clear All</a>
            </div>
        </div>
    </div>
</section>
<br><br><br><br>
<!--================End Login Box Area =================-->
{% endblock %}
{% block styleblock %}

    <style>
        .clr-btn {
            border: none;
            position: relative;
            overflow: hidden;
            color: #fff;
            padding: 0 30px;
            line-height: 50px;
            border-radius: 0px;
            display: inline-block;
            text-transform: uppercase;
            font-weight: 500;
            cursor: pointer;
            -webkit-transition: all 0.3s ease 0s;
            -moz-transition: all 0.3s ease 0s;
            -o-transition: all 0.3s ease 0s;
            transition: all 0.3s ease 0s;
            width: 75%;
            margin: 0 auto;
        }

        .pagination {
            visibility: visible;
            display: -ms-flexbox;
            display: flex;
            padding-left: 0;
            list-style: none;
            border-radius: .25rem
        }

        .pagination li {
            border: grey 1px solid
        }

        .pagination li.active {
            visibility: visible;
            width: 40px;
            line-height: 40px;
            text-align: center;
            display: inline-block;
            background: #cdcbcb;
            color: #FFFFFF;
        }

        .pagination li.disabled {
            visibility: hidden;
        }

        table {
            -ms-filter: "progid:DXImageTransform.Microsoft.Shadow(Strength=27, Direction=0, Color=#FFAC4D)"; /*IE 8*/
            -moz-box-shadow: 0 0 27px 11px rgba(255, 172, 77, 0.5); /*FF 3.5+*/
            -webkit-box-shadow: 0 0 27px 11px rgba(255, 172, 77, 0.5); /*Saf3-4, Chrome, iOS 4.0.2-4.2, Android 2.3+*/
            box-shadow: 0 0 27px 11px rgba(255, 172, 77, 0.5); /* FF3.5+, Opera 9+, Saf1+, Chrome, IE10 */
            filter: progid:DXImageTransform.Microsoft.Shadow(Strength=27, Direction=135, Color=#FFAC4D); /*IE 5.5-7*/
        }
    </style>
{% endblock %}